<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Gmail</name>
   <tag></tag>
   <elementGuidId>adb75607-4e1d-4a2f-bff0-9e6d0ef26674</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gb']/div/div/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.gb_I</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Gmail&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b4919892-a825-4815-b930-c08a5644714e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gb_I</value>
      <webElementGuid>3a5769aa-6f01-4a0d-95ca-7bfeb9911f16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Gmail </value>
      <webElementGuid>d9beda44-583b-4ee9-8c29-e207c3a6672a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pid</name>
      <type>Main</type>
      <value>23</value>
      <webElementGuid>427489e7-e6f3-441b-aeca-1a26b7b5dea7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://mail.google.com/mail/&amp;ogbl</value>
      <webElementGuid>b133219b-72ac-4eca-a6e3-de939759f73a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_top</value>
      <webElementGuid>4304b5fd-94e4-4d59-b81e-05d4b957e82f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Gmail</value>
      <webElementGuid>7cdd8c80-794b-4d1f-b998-963ae9c1347b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gb&quot;)/div[@class=&quot;gb_Dd gb_gb gb_rd&quot;]/div[1]/div[@class=&quot;gb_Kd gb_K gb_4f gb_Uf&quot;]/div[@class=&quot;gb_J gb_K&quot;]/a[@class=&quot;gb_I&quot;]</value>
      <webElementGuid>ec0e090b-8cb0-46f3-a974-7a29832662bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gb']/div/div/div/div/a</value>
      <webElementGuid>d7b9f607-d943-4806-8e9f-6980583920b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Gmail')]</value>
      <webElementGuid>9a87dd41-3e0a-485e-8c75-21c6c12a15b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Images'])[1]/preceding::a[1]</value>
      <webElementGuid>6bf089b2-f7aa-4cb7-8740-c8931f075efa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in'])[1]/preceding::a[3]</value>
      <webElementGuid>04712ae9-f09c-4fb8-b4cc-9faa92e5c2b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Gmail']/parent::*</value>
      <webElementGuid>3931e642-cb33-409e-b76f-7565dd6335ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://mail.google.com/mail/&amp;ogbl')]</value>
      <webElementGuid>34ecd62e-6a8f-4700-bb39-0df95677f850</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>5b364cfc-5698-4b22-973c-ac65f1a83330</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://mail.google.com/mail/&amp;ogbl' and (text() = 'Gmail' or . = 'Gmail')]</value>
      <webElementGuid>ea75ef1d-beb3-4303-bec2-fa32bdca5b22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
