<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Inbox1</name>
   <tag></tag>
   <elementGuidId>cd881bc4-59e5-41b0-b37a-0fb2166db5c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id=':6b']/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.aio.UKr6le</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Inbox1&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>82ae1ab9-86bb-46a1-a02f-40c983134717</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>aio UKr6le</value>
      <webElementGuid>84c11fb5-1d37-4835-9005-a1a3bcf0594c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Inbox1</value>
      <webElementGuid>3d6983be-fc08-4d52-bc5d-7ba35004d476</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:6b&quot;)/div[@class=&quot;TN bzz aHS-bnt&quot;]/div[@class=&quot;aio UKr6le&quot;]</value>
      <webElementGuid>a010f345-30b3-43b9-b9d5-921b958a626a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id=':6b']/div/div[2]</value>
      <webElementGuid>d8a7b297-46eb-4e95-920a-e3b0e434aa56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Labels'])[1]/following::div[9]</value>
      <webElementGuid>c8ee8d7a-13f4-4430-9f22-ffab3798947f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Compose'])[1]/following::div[18]</value>
      <webElementGuid>1e6637fe-030e-49b6-b750-d4f8559b0f33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Starred'])[1]/preceding::div[4]</value>
      <webElementGuid>77bc633c-b9ec-44aa-8136-8537c27e3985</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div[2]/div/div/div/div/div/div/div/div/div[2]</value>
      <webElementGuid>03eec8ce-0bc8-4009-be15-df4ce45058e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Inbox1' or . = 'Inbox1')]</value>
      <webElementGuid>e2005fb0-32b2-4342-87f3-e32218ffce2a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
